services:
  spark:
    build:
      context: .
      dockerfile: spark-server/Dockerfile
    environment:
      - SPARK_ROLE=connect
      - SPARK_CONNECT_PORT=15002
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "15002:15002"   # Spark Connect gRPC
      - "4040:4040"     # Spark UI
    volumes:
      - ./example_data:/data:ro          # datos de entrada
      - ./example_data/dest:/data/dest   # salida (Parquet/CSV/JSON/ORC)
      - ./spark-server/certs:/opt/certs:ro
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 15002 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
