services:
  spark:
    build:
      context: .
      dockerfile: spark-server/Dockerfile
    ports:
      - "15002:15002"   # Spark Connect gRPC port
      - "4040:4040"     # Spark UI (opcional)
    volumes:
#      - ./ivy2:/home/spark/.ivy2
      - ./example_data:/data
      - ./spark-server/certs:/opt/certs
    environment:
      - SPARK_NO_DAEMONIZE=true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "15002"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
