name: Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write       # push tags/commits
  issues: write         # abrir issue si falla
  pull-requests: write  # comentar en PRs

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necesario para calcular versiones
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # provisto por GitHub
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}         # opcional si publicás a npm
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: npx semantic-release
